# - name: UPDATE SERVER CONFIGURATION (1)
#   ansible.builtin.blockinfile:
#     path: "{{ server_configuration.awg_dir }}/peers.conf"
#     create: true
#     block: |
#       [Peer]
#       PublicKey = {{ user_public_key }}
#       AllowedIPs = {{ user_configuration.server_net }}{{ USER_IP_OCTET }}/32
#     marker: "# user - {{ USER_ID }}"

- name: UPDATE SERVER CONFIGURATION (1)
  ansible.builtin.blockinfile:
    path: "{{ server_configuration.awg_dir }}/server.conf"
    block: |

      # BEGIN USER - {{ USER_ID }}
      [Peer]
      PublicKey = {{ user_public_key }}
      AllowedIPs = {{ user_configuration.server_net }}{{ USER_IP_OCTET }}/32
      # END USER - {{ USER_ID }}

- name: UPDATE SERVER CONFIGURATION (2)
  ansible.builtin.shell:
    cmd: awg syncconf server <(awg-quick strip server)
    executable: /bin/bash
  args:
    chdir: "{{ server_configuration.awg_dir }}"