installation:
  deb_source: "deb https://ppa.launchpadcontent.net/amnezia/ppa/ubuntu focal main"
  deb_source_src: "deb-src https://ppa.launchpadcontent.net/amnezia/ppa/ubuntu focal main"
  kernel: "6.1.0-43-amd64"
  reboot_command: /usr/sbin/reboot
  keyserver: "keyserver.ubuntu.com"
  keyserver_id: 57290828

configuration:
  awg_keys_dir: "awg_keys"
  awg_dir: "/etc/amnezia/amneziawg"
  awg_ip: "11.1.1.1/24"
  awg_net: "11.1.1."
  dns: "1.1.1.1, 1.0.0.1"
  AllowedIPs: "0.0.0.0/0, ::/0"
  awg_port: "443"
  Jc: 4
  Jmin: 10
  Jmax: 50
  S1: 109
  S2: 52
  H1: 334175041
  H2: 171212389
  H3: 2062960224
  H4: 522745385
  PersistentKeepalive: 25